version: '2'
volumes:
  krb5kdc-data:

services:
  kdc:
    image: gcavalcante8808/krb5-server
    restart: always
    expose:
      - "88"
      - "464"
      - "749"
    environment:
      KRB5_REALM: EXAMPLE.COM
      KRB5_KDC: localhost
      KRB5_PASS: password
    volumes:
     - krb5kdc-data:/var/lib/krb5kdc
  client:
    build: docker-krb5-client
    environment:
      KRB5_REALM: EXAMPLE.COM
      KRB5_KDC: kdc
    links:
      - kdc
    
